name: Github Pages Custom Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          build-command: next start